development:
  adapter: postgresql
  encoding: unicode
  database: santa_development
  pool: 5
  host: localhost
  username: ryanmacg
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: santa_test
  pool: 5
  host: localhost
  username: ryanmacg
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: santa_test
  pool: 5
  host: localhost
  username: ryanmacg
  password: